In [91]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
import csv
from scipy import sparse
import numpy as np
import sklearn.manifold
import sklearn.datasets

In [4]:
twenty_train = fetch_20newsgroups(shuffle=True, random_state=42)

In [13]:
print (twenty_train.data[1])
print (twenty_train.target_names[1])

From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>

comp.graphics


In [22]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
vocab = count_vect.vocabulary_ 



In [63]:
print (type(vocab))


<class 'dict'>


In [68]:
print (X_train_counts.get_shape())

(11314, 130107)


In [ ]:
sparse.save_npz('data_sparse.npz', X_train_counts)


In [89]:
def save_sparse_matrix(m,filename):
    thefile = open(filename, 'w')
    nonZeros = np.array(m.nonzero())
    for entry in range(nonZeros.shape[1]):
        thefile.write("%s,%s,%s\n" % (nonZeros[0, entry], nonZeros[1, entry], m[nonZeros[0, entry], nonZeros[1, entry]]))

In [90]:
save_sparse_matrix(X_train_counts, "matrix.txt")

In [29]:
with open('dictionary_vocabulary.csv', 'w') as f:  
    w = csv.writer(f)
    w.writerows(vocab.items())

In [30]:
with open('counts.csv', 'w') as f:
    w = csv.writer(f)
    w.writerows(X_train_counts)

In [101]:
digits = sklearn.datasets.load_digits()
orig_X = digits.data
orig_Y = digits.target

every_nth_element = 1 #defult 1 == every element
X = orig_X[0::every_nth_element]
y = orig_Y[0::every_nth_element]

print("Computing t-SNE embedding")
tsne = sklearn.manifold.TSNE(n_components=3, init='pca', random_state=0)
X_tsne = tsne.fit_transform(X)

print(X_tsne)



Computing t-SNE embedding
[[  2.23272014  33.12413406 -10.51000118]
 [ 19.80122375 -23.84308434   3.22399712]
 [ 14.57578564 -12.8502779   -4.59867334]
 ..., 
 [  9.62320805  -9.15557194   3.13828921]
 [-24.75118637  25.6773262    3.5943985 ]
 [  1.26819193  -4.88418388  -1.78618717]]


NameError: name 'Y' is not defined

In [111]:

print (X_tsne.shape)
print (y_reshaped.shape)
y_reshaped = y.reshape(1797, 1)

merged_X_Y = np.concatenate((X_tsne, y_reshaped), axis=1)

(1797, 3)
(1797, 1)


array([[  2.23272014,  33.12413406, -10.51000118,   0.        ],
       [ 19.80122375, -23.84308434,   3.22399712,   1.        ],
       [ 14.57578564, -12.8502779 ,  -4.59867334,   2.        ],
       ..., 
       [  9.62320805,  -9.15557194,   3.13828921,   8.        ],
       [-24.75118637,  25.6773262 ,   3.5943985 ,   9.        ],
       [  1.26819193,  -4.88418388,  -1.78618717,   8.        ]])

In [100]:
X_tsne.tolist()
numpy.savetxt(fname='tsne.csv', X=X_tsne)


In [95]:
with open('tsne.csv', 'w') as f:
    w = csv.writer(f)
    w.writerow(X_tsne)